clientstate.cpp: Fix broken server list
Error: 'The PokerTH internet server list contains invalid data'.

Introduced with:
https://github.com/pokerth/pokerth/commit/df423249cc99adcf40b8e6e200bad9b246789839